### ISSUE TITLE
The type or namespace name "Contains" does not exist in the namespace 'ArrayUtility'

### ISSUE THREAD

**Issue by richardzzzarnoldX** [Dustyroom/flat-kit-doc#103]
Since updating to 2020.3.35f1 I get a bunch of errors, including:

Assets\FlatKit\[Render Pipeline] URP\Water\Editor\WaterEditor.cs(40,38): error CS0234: The type or namespace name 'Contains' does not exist in the namespace 'ArrayUtility' (are you missing an assembly reference?)

This is odd as here: https://docs.unity3d.com/ScriptReference/ArrayUtility.html
It clearly indicates that Contain does exist in the namespace ArrayUtility

**Comment by dustyroom-studio** [comment]
Could you please provide more context?
- Please locate the [Readme] file in Assets/Flat Kit, select it and copy the debug info from the Inspector.
- Have you installed Flat Kit URP in the URP project?
- When exactly does the issue happen?

**Comment by richardzzzarnoldX** [comment]
I think I may have just discovered the problem, it seems that I may have accidentally dragged the WaterEditor script from the scripts folder to the editor folder. Restoring it seems to fix the problem but now I have another? Assets\FlatKit\[Render Pipeline] URP\Water\Scripts\WaterEditor.cs(3,15): error CS0234: The type or namespace name 'Water' does not exist in the namespace 'FlatKit' (are you missing an assembly reference?)

**Comment by dustyroom-studio** [comment]
This is very odd. Pleasery replacing the line 40 in `Assets\FlatKit[Render Pipeline] URP\Water\Editor\WaterEditor.cs` with the following line:
```
bool keywordOn = Array.IndexOf(keywords, param) != -1;
```
